name: "code quality tests"

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  code-quality-tests:
    name: "code quality test"
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Clear Config and Cache
        run: php artisan cache:clear && php artisan config:clear

      - name: Directory Permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Larastan
        run: ./vendor/bin/phpstan analyse --xdebug
