name: Deploy

on:
  push:
    branches: ["dev"]

# Authenticate to the the server via ssh
# and run deployment script
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          ssh syncflux@${{ secrets.SERVER_IP }} 'bash -s' < ./.scripts/deploy.sh
