name: "Format Code"

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  format-code:
    name: "Format code"
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Other steps that change files in the repository- name: Laravel Pint
      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@2.1.0

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
